[project]
name = "mosaic"
version = "0.1.0"
description = "MOSAIC utilities"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Romy Beauté", email = "r.beaut@sussex.ac.uk" }]
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "torch",
    "bertopic",
    "gensim",
    "spacy",
    "sentence-transformers",
    "nltk",
    "transformers",
    "accelerate",
    "bitsandbytes",
    "datasets",
    "llama-cpp-python",
    "umap-learn",
    "hdbscan",
    "matplotlib",
    "seaborn",
    "wordcloud",
    "jupyterlab",
    "adjustText",
    "datamapplot",
    "google-generativeai"
]